FROM node:6.2

MAINTAINER akinoniku

ADD ./package.json /tmp/package.json
RUN cd /tmp && npm install

# start compile
COPY . /build

RUN rm -rf /build/node_modules \
&& mv /tmp/node_modules /build/node_modules \
&& cd /build && npm run build \
&& rm -rf /build/dist/*.map \
&& mv /build/dist /srv

ADD ./src/favicon.ico /build/dist/favicon.ico

